export const schools = [{
    _id: 1,
    lat: 18.653609,
    long: 73.880497,
    name: "RKL International",
    classList: [
        {
            name: "Math 101",
            school: "RKL International", 
            students: [
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
            ],
            attendence: {
                dates: ["10/1/2020", "10/2/2020", "10/3/2020", "10/4/2020", "10/5/2020", "10/6/2020", "10/7/2020", "10/8/2020"],
                present: [22, 21, 22, 10, 21, 20, 22, 17],
                total: 23,
            }
        },
        {
            name: "Math 126",
            school: "RKL International", 
            students: [
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
            ],
            attendence: {
                dates: ["10/1/2020", "10/2/2020", "10/3/2020", "10/4/2020", "10/5/2020", "10/6/2020", "10/7/2020", "10/8/2020"],
                present: [19, 15, 10, 19, 10, 8, 20, 17],
                total: 20
            }
        },
        {
            name: "English 235",
            school: "RKL International", 
            students: [
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
            ],
            attendence: {
                dates: ["10/1/2020", "10/2/2020", "10/3/2020", "10/4/2020", "10/5/2020", "10/6/2020", "10/7/2020", "10/8/2020"],
                present: [27, 23, 18, 28, 0, 18, 20, 0],
                total: 28
            }
        },
        {
            name: "Chem 101",
            school: "RKL International", 
            students: [
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
            ],
            attendence: {
                dates: ["10/1/2020", "10/2/2020", "10/3/2020", "10/4/2020", "10/5/2020", "10/6/2020", "10/7/2020", "10/8/2020"],
                present: [21, 22, 19, 0, 10, 22, 21, 15],
                total: 22
            }
        },
    ]
},{
    _id: 2,
    lat: 24.870523,
    long: 66.977651,
    name: "San Miguel Panan",
    classList: [
        {
            name: "Math 101",
            school: "San Miguel Panan",
            students: [
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
            ],
            attendence: {
                dates: ["10/1/2020", "10/2/2020", "10/3/2020", "10/4/2020", "10/5/2020", "10/6/2020", "10/7/2020", "10/8/2020"],
                present: [10, 22, 21, 22, 10, 21, 20, 20],
                total: 22,
            }
        },
        {
            name: "Math 126",
            school: "San Miguel Panan",
            students: [
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
            ],
            attendence: {
                dates: ["10/1/2020", "10/2/2020", "10/3/2020", "10/4/2020", "10/5/2020", "10/6/2020", "10/7/2020", "10/8/2020"],
                present: [19, 15, 10, 19, 10, 8, 0, 0],
                total: 20,
            }
        },
        {
            name: "English 235",
            school: "San Miguel Panan",
            students: [
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
            ],
            attendence: {
                dates: ["10/1/2020", "10/2/2020", "10/3/2020", "10/4/2020", "10/5/2020", "10/6/2020", "10/7/2020", "10/8/2020"],
                present: [10, 20, 27, 27, 23, 0, 18, 28],
                total: 28,
            }
        },
        {
            name: "Bio 180",
            school: "San Miguel Panan",
            students: [
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
            ],
            attendence: {
                dates: ["10/1/2020", "10/2/2020", "10/3/2020", "10/4/2020", "10/5/2020", "10/6/2020", "10/7/2020", "10/8/2020"],
                present: [20, 21, 21, 0, 10, 21, 20, 20],
                total: 21,
            }
        },
    ]
}]
