export const schools = [{
    _id: 1,
    lat: 18.653609,
    long: 73.880497,
    name: "RKL International",
    classList: [
        {
            name: "Math 101",
            school: "RKL International", 
            students: [
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
            ],
            attendence: {
                dates: ["10/1/2020", "10/2/2020", "10/3/2020", "10/4/2020", "10/5/2020", "10/6/2020", "10/7/2020", "10/8/2020"],
                present: [22, 21, 22, 10, 21, 20, 22, 17],
                total: 23,
            }
        },
        {
            name: "Math 126",
            school: "RKL International", 
            students: [
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
            ],
            attendence: {
                dates: ["10/1/2020", "10/2/2020", "10/3/2020", "10/4/2020", "10/5/2020", "10/6/2020", "10/7/2020", "10/8/2020"],
                present: [19, 15, 10, 19, 10, 8, 20, 17],
                total: 20
            }
        },
        {
            name: "English 235",
            school: "RKL International", 
            students: [
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
            ],
            attendence: {
                dates: ["10/1/2020", "10/2/2020", "10/3/2020", "10/4/2020", "10/5/2020", "10/6/2020", "10/7/2020", "10/8/2020"],
                present: [27, 23, 18, 28, 0, 18, 20, 0],
                total: 28
            }
        },
        {
            name: "Chem 101",
            school: "RKL International", 
            students: [
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
            ],
            attendence: {
                dates: ["10/1/2020", "10/2/2020", "10/3/2020", "10/4/2020", "10/5/2020", "10/6/2020", "10/7/2020", "10/8/2020"],
                present: [21, 22, 19, 0, 10, 22, 21, 15],
                total: 22
            }
        },
    ]
},{
    _id: 2,
    lat: 24.870523,
    long: 66.977651,
    name: "San Miguel Panan",
    classList: [
        {
            name: "Math 101",
            school: "San Miguel Panan",
            students: [
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
            ],
            attendence: {
                dates: ["10/1/2020", "10/2/2020", "10/3/2020", "10/4/2020", "10/5/2020", "10/6/2020", "10/7/2020", "10/8/2020"],
                present: [10, 22, 21, 22, 10, 21, 20, 20],
                total: 22,
            }
        },
        {
            name: "Math 126",
            school: "San Miguel Panan",
            students: [
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
            ],
            attendence: {
                dates: ["10/1/2020", "10/2/2020", "10/3/2020", "10/4/2020", "10/5/2020", "10/6/2020", "10/7/2020", "10/8/2020"],
                present: [19, 15, 10, 19, 10, 8, 0, 0],
                total: 20,
            }
        },
        {
            name: "English 235",
            school: "San Miguel Panan",
            students: [
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
            ],
            attendence: {
                dates: ["10/1/2020", "10/2/2020", "10/3/2020", "10/4/2020", "10/5/2020", "10/6/2020", "10/7/2020", "10/8/2020"],
                present: [10, 20, 27, 27, 23, 0, 18, 28],
                total: 28,
            }
        },
        {
            name: "Bio 180",
            school: "San Miguel Panan",
            students: [
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "male"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
                {gender: "female"},
            ],
            attendence: {
                dates: ["10/1/2020", "10/2/2020", "10/3/2020", "10/4/2020", "10/5/2020", "10/6/2020", "10/7/2020", "10/8/2020"],
                present: [20, 21, 21, 0, 10, 21, 20, 20],
                total: 21,
            }
        },
    ]
}]

export const Attendance = [
    {
        PartitionKey: '1',
        TimeStamp: '2020-11-02T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-1',
        Lattitude: 18.653609,
        Longitute: 73.880497,
        Present: true,
        StudentId: 'student-1',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '1',
        TimeStamp: '2020-11-02T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-1',
        Lattitude: 18.653609,
        Longitute: 73.880497,
        Present: true,
        StudentId: 'student-2',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '1',
        TimeStamp: '2020-11-02T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-1',
        Lattitude: 18.653609,
        Longitute: 73.880497,
        Present: true,
        StudentId: 'student-3',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '1',
        TimeStamp: '2020-11-03T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-1',
        Lattitude: 18.653609,
        Longitute: 73.880497,
        Present: false,
        StudentId: 'student-3',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '1',
        TimeStamp: '2020-11-03T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-1',
        Lattitude: 18.653609,
        Longitute: 73.880497,
        Present: true,
        StudentId: 'student-2',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '1',
        TimeStamp: '2020-11-03T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-1',
        Lattitude: 18.653609,
        Longitute: 73.880497,
        Present: true,
        StudentId: 'student-1',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '1',
        TimeStamp: '2020-11-04T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-1',
        Lattitude: 18.653609,
        Longitute: 73.880497,
        Present: false,
        StudentId: 'student-3',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '1',
        TimeStamp: '2020-11-04T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-1',
        Lattitude: 18.653609,
        Longitute: 73.880497,
        Present: true,
        StudentId: 'student-2',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '1',
        TimeStamp: '2020-11-04T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-1',
        Lattitude: 18.653609,
        Longitute: 73.880497,
        Present: true,
        StudentId: 'student-1',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '2',
        TimeStamp: '2020-11-04T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-2',
        Lattitude: 24.870523,
        Longitute: 66.977651,
        Present: true,
        StudentId: 'student-5',
        TeacherId: 'teacher-2',
    },
    {
        PartitionKey: '2',
        TimeStamp: '2020-11-04T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-2',
        Lattitude: 24.870523,
        Longitute: 66.977651,
        Present: false,
        StudentId: 'student-6',
        TeacherId: 'teacher-2',
    },
    {
        PartitionKey: '2',
        TimeStamp: '2020-11-01T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-2',
        Lattitude: 24.870523,
        Longitute: 66.977651,
        Present: false,
        StudentId: 'student-5',
        TeacherId: 'teacher-2',
    },
    {
        PartitionKey: '2',
        TimeStamp: '2020-11-01T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-2',
        Lattitude: 24.870523,
        Longitute: 66.977651,
        Present: false,
        StudentId: 'student-6',
        TeacherId: 'teacher-2',
    },

    {
        PartitionKey: '3',
        TimeStamp: '2020-11-01T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: false,
        StudentId: 'student-7',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-01T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: false,
        StudentId: 'student-8',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-01T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: false,
        StudentId: 'student-9',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-01T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: false,
        StudentId: 'student-10',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-01T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: false,
        StudentId: 'student-11',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-01T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: false,
        StudentId: 'student-12',
        TeacherId: 'teacher-1',
    },
    
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-10T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: false,
        StudentId: 'student-7',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-10T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: true,
        StudentId: 'student-8',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-10T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: false,
        StudentId: 'student-9',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-10T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: false,
        StudentId: 'student-10',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-10T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: false,
        StudentId: 'student-11',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-10T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: true,
        StudentId: 'student-12',
        TeacherId: 'teacher-1',
    },

    {
        PartitionKey: '3',
        TimeStamp: '2020-11-11T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: true,
        StudentId: 'student-7',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-11T22:12:53.4746639Z',
        BlobURL: true,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: false,
        StudentId: 'student-8',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-11T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: false,
        StudentId: 'student-9',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-11T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: true,
        StudentId: 'student-10',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-11T22:12:53.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: true,
        StudentId: 'student-11',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-11T22:12:10.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-3',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: false,
        StudentId: 'student-12',
        TeacherId: 'teacher-1',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-11T22:12:10.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-4',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: true,
        StudentId: 'student-12',
        TeacherId: 'teacher-2',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-11T22:12:10.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-4',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: false,
        StudentId: 'student-11',
        TeacherId: 'teacher-2',
    },
    {
        PartitionKey: '3',
        TimeStamp: '2020-11-11T22:12:10.4746639Z',
        BlobURL: null,
        ClassRoomId: 'class-room-4',
        Lattitude: 20.870523,
        Longitute: 60.977651,
        Present: true,
        StudentId: 'student-10',
        TeacherId: 'teacher-2',
    },
];   

export const studentData = [
    {
        id: "student-1",
        Gender: "male"
    },
    {
        id: "student-2",
        Gender: "female"
    },
    {
        id: "student-3",
        Gender: "other"
    },
    {
        id: "student-4",
        Gender: "male"
    },
    {
        id: "student-5",
        Gender: "male"
    },
    {
        id: "student-6",
        Gender: "other"
    },
    {
        id: "student-7",
        Gender: "female"
    },
    {
        id: "student-8",
        Gender: "female"
    },
    {
        id: "student-9",
        Gender: "female"
    },
    {
        id: "student-10",
        Gender: "female"
    },
    {
        id: "student-11",
        Gender: "female"
    },
    {
        id: "student-12",
        Gender: "female"
    },
    {
        id: "student-13",
        Gender: "other"
    },
]

export const schoolData = [
    {
        id: "1",
        city: "Test1"
    },
    {
        id: "2",
        city: "Test2"
    },
    {
        id: "3",
        city: "Test2"
    },
    {
        id: "4",
        city: "Test1"
    },
    {
        id: "5",
        city: "Test4"
    },
]